package com.jsp_cns_mon.pub_jsp_cns_all_bre_data_rule_editing;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public test() {
    }




}